### ISSUE TITLE
Can you replace the font with SFMono-Medium.otf ???

### ISSUE THREAD

**Issue by good-good-study** [johncodeos-blog/XcodeKotlinColorScheme#2]
As shown in the figure:
AndroidStudio on the left, XCode on the right.

Obviously, the one on the left is not very good-looking and the contrast is not high, it is better to make the font bold, can you replace the font with SFMono-Medium.otf ???

<img width="1389" alt="截屏2022-06-11 12 49 35" src="https://user-images.githubusercontent.com/20188392/173173138-5dbddf10-9a2c-4199-995c-dadf0323149f.png">

**Comment by johncodeos** [comment]
You're right! SF Mono Medium is now the default font on Xcode. I replaced the file.
Thank you! 👍
